---
- name: run container 
  docker:
    name: nightclazz_spark_ml
    image: herveriviere/spark_zeppelin_standalone:v4
    state: started
    ports:
    - "8080:8080"
    - "8084:8084"
    env:
        SPARK_WORKER_CORES: 3
        SPARK_WORKER_MEMORY: 800m
    volumes:
    - /home/ec2-user/nightclazz_spark_ml:/home/udl_spark

- pause: seconds=10


- name: Import titanic notebook 
  shell: wget https://raw.githubusercontent.com/hriviere/nightclazz_spark_ml/master/notebook_zeppelin/Titanic.json && content=`cat Titanic.json` && curl --data ''"$content"'' http://localhost:8084/api/notebook/import && rm Titanic.json
  args:
    chdir: /home/ec2-user/nightclazz_spark_ml/notebook
    creates: import_titanic.ok

