---
- name: instanciate spark_zeppelin container
  hosts: nightclazz
  become: yes

  roles:
    - common
    - spark_zeppelin

#TODO...
#sudo wget https://raw.githubusercontent.com/hriviere/nightclazz_spark_ml/master/notebook_zeppelin/Titanic.json
#content=`cat Titanic.json `
#curl --data ''"$content"'' http://localhost:8084/api/notebook/import
